// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentManagementApi.Data;

#nullable disable

namespace StudentManagementApi.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    [Migration("20251223214615_studentsdata")]
    partial class studentsdata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentManagementApi.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 21,
                            CreatedAt = new DateTime(2025, 12, 24, 1, 46, 13, 807, DateTimeKind.Local).AddTicks(3696),
                            Email = "nin.ramishvili4@gmail.com",
                            FirstName = "Nino",
                            LastName = "Ramishvili"
                        },
                        new
                        {
                            Id = 2,
                            Age = 22,
                            CreatedAt = new DateTime(2025, 12, 24, 1, 46, 13, 807, DateTimeKind.Local).AddTicks(3767),
                            Email = "1234@mail.com",
                            FirstName = "Jane",
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 4,
                            Age = 19,
                            CreatedAt = new DateTime(2025, 12, 24, 1, 46, 13, 807, DateTimeKind.Local).AddTicks(3770),
                            Email = "abc@gmail.com",
                            FirstName = "Alice",
                            LastName = "ramishvili"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
